# OUTPUT_LANG_INDEX start from 0
generator-localization:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1G_URjFT5ja3OwjMSgMuDFS5dzk2YEiQCzPvqbyENrTA GID_ID=Bridge OUTPUT_FOLDER=../src/language/locales/en/defaults.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=1G_URjFT5ja3OwjMSgMuDFS5dzk2YEiQCzPvqbyENrTA GID_ID=Bridge OUTPUT_FOLDER=../src/language/locales/jp/defaults.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=5 SPREADSHEET_ID=1G_URjFT5ja3OwjMSgMuDFS5dzk2YEiQCzPvqbyENrTA GID_ID=Bridge OUTPUT_FOLDER=../src/language/locales/cn/defaults.json

